name: "Multi Event Pipeline / Workflow" # Name of the pipeline / workflow

on:
    push: # Event: Whenever there is a push to the repository on main or test branches
        branches:
            - main
            - test
    schedule: # Event: Scheduled trigger of the workflow at specific times
        - cron: '0 0 * * 0' # At 00:00 on Sundays
    pull_request: # Event: Whenever there is a pull request to the repository on main branch
        branches:
            - main
        types: 
            - closed
            - opened
    workflow_dispatch: # Event: Manual trigger of the workflow from GitHub Actions tab


jobs:
    on-push: # Job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "This job runs on push to main or test branches"

    on-pull-request: # Job name
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "This job runs on pull request to main branch"

    on-pull-request-opened: # Job name
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request opened"
              run: echo "This job runs when a pull request to main branch is opened"

    on-pull-request-closed: # Job name
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed"
              run: echo "This job runs when a pull request to main branch is closed"

    on-workflow-dispatch: # Job name
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on manual trigger"
              run: echo "This job runs when manually triggered from GitHub Actions tab"

    on-schedule: # Job name
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on schedule"
              run: echo "This job runs on scheduled trigger (every Sunday at midnight)"